# Agents
query AllAgents {
  allAgents {
    id
    name
    note
    createdAt
  }
}

query GetAgentsWithLocation {
  agentsWithLocation {
    id
    name
    locations {
      id
      name
      value
    }
  }
}

mutation CreateAgent($name: String!, $note: String) {
  createAgent(name: $name, note: $note) {
    id
    name
    note
    createdAt
  }
}


# # Locations
query LocationsByAgent($agentId: Uuid!) {
  locationsByAgent(agentId: $agentId) {
    id
    agentId
    name
    value
  }
}

mutation CreateLocation($agentId: Uuid!, $name: String!, $value: String!) {
  createLocation(agentId: $agentId, name: $name, value: $value) {
    id
    agentId
    name
    value
  }
}
