# Recipes

fragment RecipeFragment on Recipe {
  id
  agentId
  name
  note
  createdAt
}

fragment ResourceSpecificationFragment on ResourceSpecification {
  id
  agentId
  name
  note
  createdAt
  resourceType
  unitOfMeasure
}

fragment RelationsFragment on ProcessRelation {
  id
  recipeId
  recipeProcessId
  predecessor
}


query RecipesByAgent($agentId: Uuid!) {
  recipesByAgent(agentId: $agentId) {
    recipe {
      ...RecipeFragment
    }
    resourceSpecifications {
      ...ResourceSpecificationFragment
    }
    relations {
      ...RelationsFragment
    }
  }
}

query RecipeById($recipeId: Uuid!) {
  recipeById(recipeId: $recipeId) {
    recipe {
      ...RecipeFragment
    }
    resourceSpecifications {
      ...ResourceSpecificationFragment
    }
    relations {
      ...RelationsFragment
    }
  }
}

mutation CreateRecipe(
  $agentId: Uuid!,
  $name: String!,
  $note: String,
  $recipeResources: [Uuid!]!
) {
  createRecipe(
    agentId: $agentId,
    name: $name,
    note: $note,
    recipeResources: $recipeResources
  ) {
    recipe {
      ...RecipeFragment
    }
    resourceSpecifications {
      ...ResourceSpecificationFragment
    }
    relations {
      ...RelationsFragment
    }
  }
}

mutation SetRecipeProcesses(
  $recipeId: Uuid!,
  $processes: [InputProcessRelation!]!
) {
  setRecipeProcesses(
    recipeId: $recipeId,
    processes: $processes
  ) {
    recipeProcess {
      id
      recipeId
      recipeTemplateId
      name
    }
    predecessors
  }
}